config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/User.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\Auth\DefaultPasswordHasher;

class User extends Entity
{

    protected $_accessible = [
        '*' => true,
        'id' => false
    ];

    protected function _setPassword($password){
        $hasher = new DefaultPasswordHasher();
        return $hasher->hash($password);
    }
}

src/Model/Table/UsersTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

class UsersTable extends Table
{

    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('users');
        $this->setDisplayField('nome');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Cursos', [
            'foreignKey' => 'curso_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Perfis', [
            'foreignKey' => 'perfil_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('Atividades', [
            'foreignKey' => 'user_id'
        ]);
    }

    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('nome', 'create')
            ->notEmpty('nome');

        $validator
            ->requirePresence('username', 'create')
            ->notEmpty('username');

        $validator
            ->requirePresence('password', 'create')
            ->notEmpty('password');

        $validator
            ->requirePresence('cpf', 'create')
            ->notEmpty('cpf');

        $validator
            ->date('data_nascimento')
            ->allowEmpty('data_nascimento');

        $validator
            ->email('email')
            ->requirePresence('email', 'create')
            ->notEmpty('email');

        $validator
            ->integer('status')
            ->requirePresence('status', 'create')
            ->notEmpty('status');

        $validator
            ->integer('criado_por')
            ->requirePresence('criado_por', 'create')
            ->notEmpty('criado_por');

        $validator
            ->integer('modificado_por')
            ->requirePresence('modificado_por', 'create')
            ->notEmpty('modificado_por');

        return $validator;
    }

    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['username']));
        $rules->add($rules->isUnique(['email']));
        $rules->add($rules->existsIn(['curso_id'], 'Cursos'));
        $rules->add($rules->existsIn(['perfil_id'], 'Perfis'));

        return $rules;
    }
}

src/Controller/UsersController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;
use Cake\Auth\Auth;
use Cake\ORM\TableRegistry;

class UsersController extends AppController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);
        $this->Auth->allow(['logout']);
    }

    public function index()
    {
        $users = $this->Users->find()->contain(['Cursos','Perfis'])->where(['Users.status' => 1])->all();
        
        $this->set(compact('users'));
        $this->set('_serialize', ['users']);
    }

 
    public function view($id = null)
    {
        $user = $this->Users->get($id, [
            'contain' => ['Cursos', 'Perfis', 'Atividades']
        ]);

        $this->set('user', $user);
        $this->set('_serialize', ['user']);
    }

    public function add()
    {
        $user = $this->Users->newEntity();
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->getData());
            $user->status = 1;
            $user->criado_por = $this->retornarIdUsuarioAtivo();
            $user->modificado_por = $this->retornarIdUsuarioAtivo();;
            $user->data_nascimento = trim(date('Y-m-d', strtotime(str_replace('/', '-', $this->request->data['data_nascimento']))));
            if ($this->Users->save($user)) {
                $this->Flash->success(__('Usuário salvo.'));
                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('Erro ao salvar usuário'));
            return $this->redirect(['action' => 'index']);
        }
        $cursos = $this->Users->Cursos->find('list', ['limit' => 200]);
        $perfis = $this->Users->Perfis->find('list', ['limit' => 200]);

        $this->set(compact('user', 'cursos', 'perfis'));
        $this->set('_serialize', ['user']);
    }

    public function edit($id = null)
    {
        $user = $this->Users->get($id, [
            'contain' => []
        ]);
        $user->data_nascimento = trim(date('d/m/Y', strtotime(str_replace('-', '/', $user->data_nascimento))));
        if ($this->request->is(['patch', 'post', 'put'])) {
            $user = $this->Users->patchEntity($user, $this->request->getData());
            $user->data_nascimento = trim(date('Y-m-d', strtotime(str_replace('/', '-', $this->request->data['data_nascimento']))));
            $user->modificado_por = $this->retornarIdUsuarioAtivo();;
            if ($this->Users->save($user)) {
                $this->Flash->success(__('Usuário salvo.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('Erro ao salvar usuário.'));
            return $this->redirect(['action' => 'index']);
        }
        $cursos = $this->Users->Cursos->find('list', ['limit' => 200]);
        $perfis = $this->Users->Perfis->find('list', ['limit' => 200]);


        $this->set(compact('user', 'cursos', 'perfis'));
        $this->set('_serialize', ['user']);
    }

    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $user = $this->Users->get($id);
        $user->status = 0;
        if ($this->Users->save($user)) {
            $this->Flash->success(__('The user has been deleted.'));
        } else {
            $this->Flash->error(__('The user could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }

    public function login(){
        $this->viewBuilder()->layout("inicial");
        if($this->request->is('post')){
            $user = $this->Auth->identify();
            if($user){
                $this->Auth->setUser($user);
                return $this->redirect(['controller' => 'Users','action'=>'index']);
            }else{
                //$this->Flash->error(__('Usuário ou senha inválida, tente novamente'));
                return $this->redirect(['controller' => 'Users','action'=>'login']);
            }
        }
    }

    public function logout(){
        return $this->redirect($this->Auth->logout());
    }
}

src/Template/Users/add.ctp
<?= $this->Html->css('font-awesome.css') ?>
<?= $this->Html->css('nprogress.css') ?>
<?= $this->Html->css('datepicker.css') ?>

<?php echo $this->Html->script('input-maskmoney') ?>
<?php echo $this->Html->script('bootstrap-datepicker') ?>
<?php echo $this->Html->script('jquery.smartWizard') ?>
<?php echo $this->Html->script('nprogress') ?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Adicionar Usuário</h4>
</div>
<?php echo $this->Form->create($user,['role'=>'form', 'id'=>'FormAddUser','method'=>'post']); ?>
<div class="modal-body">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <?= $this->Flash->render() ?>
        <div class="clearfix"></div>
    </div> 
    <div class="row">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('nome', ['class'=>'form-control', 'id'=>'nome']); ?>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('cpf', ['class'=>'form-control','id' => 'cpf','data-mask'=>'999.999.999-99', 'label' => 'Cpf','type' => 'text']); ?>
            </div>
           
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('email', ['class'=>'form-control', 'id'=>'email','type' => 'email']); ?>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('data_nascimento', ['label' => 'Data Nascimento','type'=>'text', 'class' => 'form-control','id'=>'dataNascimento','data-date-format'=>'dd/mm/yyyy']); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('username', ['class'=>'form-control', 'id'=>'username','label' => 'Login']); ?>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('password', ['class'=>'form-control', 'label'=>'Senha','type' => 'password']); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('curso_id', ['class'=>'form-control', 'id'=>'curso','options' => $cursos,'type' => 'select','empty' => 'Selecione um curso']); ?>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('perfil_id', ['class'=>'form-control', 'id'=>'perfil','options' => $perfis,'type' => 'select','empty' => 'Selecione um perfil']); ?>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <?php echo $this->Form->button('Salvar',['class'=>'btn btn-success btn-sm']); ?>
            <?php echo $this->Form->button('Limpar',['type'=>'reset', 'class'=>'btn btn-warning btn-sm']); ?>
        </div>
    </div>  
</div>
<?php echo $this->Form->end(); ?>


<script>
    $(function () { 
        $(document).ready(function () {
            $('#dataNascimento').datepicker().on('changeDate', function(ev)
            {                 
                 $('.datepicker').hide();
            });
        }); 
        $('body').on('hidden.bs.modal', '.modal', function () {
            $(this).removeData('bs.modal');
        });
        $("#FormAddUser").submit(function(){
            if(!validarForm()){
                return false;
            }else{
                return true;
            }
        });
    });

    function validarForm(){
        if($("#nome").val() == ""){
            alert("Preencha o nome do usuário!");
            return false;
        }else if($("#cpf").val() == ""){
            alert("Preencha o cpf do usuário!");
            return false;
        }else if($("#dataNascimento").val() == ""){
            alert("Preencha a data de nascimento do usuário!");
            return false;
        }else if($("#email").val() == ""){
            alert("Preencha o email do usuário!");
            return false;
        }else if($("#username").val() == ""){
            alert("Preencha o login do usuário!");
            return false;
        }else if($("#password").val() == ""){
            alert("Preencha a senha do usuário!");
            return false;
        }else if($("#curso").val() == ""){
            alert("Preencha o curso do usuário!");
            return false;
        }else if($("#perfil").val() == ""){
            alert("Preencha o perfil do usuário!");
            return false;
        }else{
            return true;
        }
    }
</script>

src/Template/Users/edit.ctp
<?= $this->Html->css('font-awesome.css') ?>
<?= $this->Html->css('nprogress.css') ?>
<?= $this->Html->css('datepicker.css') ?>

<?php echo $this->Html->script('input-maskmoney') ?>
<?php echo $this->Html->script('bootstrap-datepicker') ?>
<?php echo $this->Html->script('jquery.smartWizard') ?>
<?php echo $this->Html->script('nprogress') ?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Adicionar Usuário</h4>
</div>
<?php echo $this->Form->create($user,['role'=>'form', 'id'=>'FormAddUser','method'=>'post']); ?>
<div class="modal-body">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <?= $this->Flash->render() ?>
        <div class="clearfix"></div>
    </div> 
    <div class="row">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('nome', ['class'=>'form-control', 'id'=>'nome']); ?>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('cpf', ['class'=>'form-control','id' => 'cpf','data-mask'=>'999.999.999-99', 'label' => 'Cpf','type' => 'text']); ?>
            </div>
           
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('email', ['class'=>'form-control', 'id'=>'email','type' => 'email']); ?>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('data_nascimento', ['label' => 'Data Nascimento','type'=>'text', 'class' => 'form-control','id'=>'dataNascimento','data-date-format'=>'dd/mm/yyyy']); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('username', ['class'=>'form-control', 'id'=>'username','label' => 'Login']); ?>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('password', ['class'=>'form-control', 'label'=>'Senha','type' => 'password']); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('curso_id', ['class'=>'form-control', 'id'=>'curso','options' => $cursos,'type' => 'select','empty' => 'Selecione um curso']); ?>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->Form->input('perfil_id', ['class'=>'form-control', 'id'=>'perfil','options' => $perfis,'type' => 'select','empty' => 'Selecione um perfil']); ?>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <?php echo $this->Form->button('Salvar',['class'=>'btn btn-success btn-sm']); ?>
            <?php echo $this->Form->button('Limpar',['type'=>'reset', 'class'=>'btn btn-warning btn-sm']); ?>
        </div>
    </div>  
</div>
<?php echo $this->Form->end(); ?>


<script>
    $(function () { 
        $(document).ready(function () {
            $('#dataNascimento').datepicker().on('changeDate', function(ev)
            {                 
                 $('.datepicker').hide();
            });
        }); 
        $('body').on('hidden.bs.modal', '.modal', function () {
            $(this).removeData('bs.modal');
        });
        $("#FormAddUser").submit(function(){
            if(!validarForm()){
                return false;
            }else{
                return true;
            }
        });
    });

    function validarForm(){
        if($("#nome").val() == ""){
            alert("Preencha o nome do usuário!");
            return false;
        }else if($("#cpf").val() == ""){
            alert("Preencha o cpf do usuário!");
            return false;
        }else if($("#dataNascimento").val() == ""){
            alert("Preencha a data de nascimento do usuário!");
            return false;
        }else if($("#email").val() == ""){
            alert("Preencha o email do usuário!");
            return false;
        }else if($("#username").val() == ""){
            alert("Preencha o login do usuário!");
            return false;
        }else if($("#password").val() == ""){
            alert("Preencha a senha do usuário!");
            return false;
        }else if($("#curso").val() == ""){
            alert("Preencha o curso do usuário!");
            return false;
        }else if($("#perfil").val() == ""){
            alert("Preencha o perfil do usuário!");
            return false;
        }else{
            return true;
        }
    }
</script>

src/Template/Users/index.ctp
<?php echo $this->Html->css('dataTables.bootstrap.css') ?>
<?php echo $this->Html->css('responsive.bootstrap.css') ?>
<?php echo $this->Html->css('buttons.bootstrap.css') ?>
<?php echo $this->Html->css('fixedHeader.bootstrap.css') ?>
<?php echo $this->Html->css('scroller.bootstrap.css') ?>

<div class="page-title">
    <div class="title_left">
        <h3>Usuários</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <?php echo $this->Html->link('Adicionar', ['action'=>'add'], ['escape'=>false,'class' => 'btn btn-success btn-sm', 'data-toggle'=>'modal','data-target'=>'#AddUser']); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <?= $this->Flash->render() ?>
                    <div class="clearfix"></div>
                </div> 
                <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info">
                    <thead>
                        <tr role="row">
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Login</th>
                            <th>Cpf</th>
                            <th>Curso</th>
                            <th>Perfil</th>
                            <th>Data Nascimento</th>
                            <th>Email</th>
                            <th style="width: 100px;">Opções</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($users as $user): ?>
                            <tr>
                                <td><?php echo $user->id; ?></td>
                                <td><?php echo $user->nome; ?></td>
                                <td><?php echo $user->login; ?></td>
                                <td><?php echo $user->cpf; ?></td>
                                <td><?php echo $user->curso->nome; ?></td>
                                <td><?php echo $user->perfi->nome; ?></td>
                                <td><?php 
                                        if(!empty($user->data_nascimento)){
                                            echo $user->data_nascimento->format('d/m/Y');
                                        } 
                                    ?>        
                                </td>
                                <td><?php echo $user->email; ?></td>
                                <td>
                                    <?php echo $this->Html->link('Editar', ['action'=>'edit',$user->id], ['escape'=>false,'class' => 'btn btn-warning btn-xs', 'data-toggle'=>'modal','data-target'=>'#EditUser']); ?>
                                    <?php 
                                        if($user->id != 1)
                                            echo $this->Form->postLink('Excluir',['action' => 'delete', $user->id], ['type'=>'button','class' => 'btn btn-danger btn-xs', 'escape' => false,'confirm' =>'Tem certeza que deseja excluir esse usuário?']); 
                                    ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade bs-example-modal" tabindex="-1" role="dialog" aria-hidden="true"  id="AddUser">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
</div>
<div class="modal fade bs-example-modal" tabindex="-1" role="dialog" aria-hidden="true"  id="EditUser">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
</div>
<?php echo $this->Html->script('jquery.dataTables') ?>
<?php echo $this->Html->script('dataTables.bootstrap') ?>
<?php echo $this->Html->script('dataTables.responsive') ?>
<?php echo $this->Html->script('responsive.bootstrap') ?>

src/Template/Users/login.ctp
<div class="logo_section">
  <div style="background-color:#1ABB9C">
      <center><?php echo $this->Html->image('logo.jpg', ['width'=>'300px','heigth'=>'300px']); ?></center>
  </div>
</div>
<div class="login_wrapper">
    <div class="animate form login_form">
        <section class="login_content">
            <?= $this->Form->create() ?>
                <div>
                    <center><?php //echo $this->Html->image('logo.png', ['width'=>'150px']); ?></center>
                </div>
                <br>
                <div>
                    <?= $this->Form->input('username',['class'=>'form-control', 'placeholder'=>'Login','label'=>false,'style'=>'text-align:center']) ?>
                </div>
                <div>
                    <?= $this->Form->input('password',['class'=>'form-control', 'placeholder'=>'Senha','label'=>false, 'type'=>'password', 'style'=>'text-align:center']); ?>
                </div>
                <div class="clearfix"></div>
                <div>
                    <?= $this->Form->button('Entrar',['class'=>'btn btn-block btn-primary','style'=>'background-color:#1ABB9C; border:none;']) ?>
                </div>
            <?= $this->Form->end(); ?>
        </section>
    </div>
</div>