config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Mensagen.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Mensagen Entity
 *
 * @property int $id
 * @property string $titulo
 * @property string $mensagem
 * @property int $user_destino_id
 * @property int $status
 * @property int $criado_por
 * @property \Cake\I18n\FrozenTime $created
 * @property int $modificado_por
 * @property \Cake\I18n\FrozenTime $modified
 *
 * @property \App\Model\Entity\UserDestino $user_destino
 */
class Mensagen extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];
}

src/Model/Table/MensagensTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Mensagens Model
 *
 * @property \App\Model\Table\UserDestinosTable|\Cake\ORM\Association\BelongsTo $UserDestinos
 *
 * @method \App\Model\Entity\Mensagen get($primaryKey, $options = [])
 * @method \App\Model\Entity\Mensagen newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Mensagen[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Mensagen|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Mensagen patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Mensagen[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Mensagen findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class MensagensTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('mensagens');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Users', [
            'foreignKey' => 'user_destino_id',
            'joinType' => 'INNER'
        ]);

        $this->belongsTo('UsuarioCriador', [
            'className' => 'Users',
            'foreignKey' => 'criado_por',
            'joinType' => 'INNER'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('titulo', 'create')
            ->notEmpty('titulo');

        $validator
            ->requirePresence('mensagem', 'create')
            ->notEmpty('mensagem');

        $validator
            ->integer('status')
            ->requirePresence('status', 'create')
            ->notEmpty('status');

        $validator
            ->integer('criado_por')
            ->requirePresence('criado_por', 'create')
            ->notEmpty('criado_por');

        $validator
            ->integer('modificado_por')
            ->requirePresence('modificado_por', 'create')
            ->notEmpty('modificado_por');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_destino_id'], 'Users'));

        return $rules;
    }
}

src/Controller/MensagensController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
class MensagensController extends AppController
{

    public function index()
    {
        $this->paginate = [
            'contain' => ['Users']
        ];
        //$mensagens = $this->Mensagens->find()->contain(['Users'])->where(['Mensagens.user_destino_id' => 1,'Mensagens.status >' => 0])->order(['Mensagens.created DESC'])->all();
        $mensagens = $this->Mensagens->find()->contain(['Users','UsuarioCriador'])->where(['Mensagens.status >' => 0,'Mensagens.user_destino_id' => $this->retornarIdUsuarioAtivo()])->all();
        //pr($mensagens);exit;
        $this->set(compact('mensagens'));
        $this->set('_serialize', ['mensagens']);
    }

    public function view($id = null)
    {
        $mensagen = $this->Mensagens->get($id, [
            'contain' => ['Users']
        ]);

        $this->set('mensagen', $mensagen);
        $this->set('_serialize', ['mensagen']);
    }

    public function add()
    {
        $mensagem = $this->Mensagens->newEntity();
        if ($this->request->is('post')) {
            $mensagem = $this->Mensagens->patchEntity($mensagem, $this->request->getData());
            $mensagem->status = 1;
            $mensagem->criado_por = $this->retornarIdUsuarioAtivo();
            $mensagem->modificado_por = $this->retornarIdUsuarioAtivo();
            
            if ($this->Mensagens->save($mensagem)) {
                $this->Flash->success(__('Mensagem salva.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('Erro ao enviar mensagem.'));
        }
        $userDestinos = $this->Mensagens->Users->find('list')->where(['Users.status' => 1]);
        $this->set(compact('mensagem', 'userDestinos'));
        $this->set('_serialize', ['mensagem']);
    }

    public function edit($id = null)
    {
        $mensagem = $this->Mensagens->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $mensagem = $this->Mensagens->patchEntity($mensagem, $this->request->getData());
            $mensagem->modificado_por = $this->retornarIdUsuarioAtivo();
            if ($this->Mensagens->save($mensagem)) {
                $this->Flash->success(__('Mensagem salva.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('Erro ao enviar mensagem'));
        }
        $userDestinos = $this->Mensagens->Users->find('list')->where(['Users.id <>'=> 1]);
        $this->set(compact('mensagem', 'userDestinos'));
        $this->set('_serialize', ['mensagem']);
    }

 
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $mensagen = $this->Mensagens->get($id);
        $mensagen->status = 0;
        $mensagem->modificado_por = $this->retornarIdUsuarioAtivo();
        if ($this->Mensagens->save($mensagen)) {
            $this->Flash->success(__('Mensagem apagada.'));
        } else {
            $this->Flash->error(__('Erro ao apagar Mensagem.'));
        }

        return $this->redirect(['action' => 'index']);
    }

    public function enviadas()
    {
        $this->paginate = [
            'contain' => ['Users']
        ];
        $mensagens = $this->Mensagens->find()->contain(['Users','UsuarioCriador'])->where(['Mensagens.criado_por' => $this->retornarIdUsuarioAtivo(),'Mensagens.status >'=> 0])->order(['Mensagens.created DESC'])->all();

        $this->set(compact('mensagens'));
        $this->set('_serialize', ['mensagens']);
    }

    public function lerMensagem($id = null)
    {
        $mensagem = $this->Mensagens->get($id);
        $mensagem->status = 2;
        $mensagem->modificado_por = $this->retornarIdUsuarioAtivo();
        if ($this->Mensagens->save($mensagem)) {
            $this->Flash->success(__('Mensagem marcada como lida'));
        } else {
            $this->Flash->error(__('Erro ao alterar status da mensagem.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Mensagens/add.ctp
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Enviar Mensagem</h4>
</div>
<?php echo $this->Form->create($mensagem,['role'=>'form', 'id'=>'FormAddMensagem','method'=>'post']); ?>
<div class="modal-body">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <?= $this->Flash->render() ?>
        <div class="clearfix"></div>
    </div> 
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <?php echo $this->Form->input('titulo', ['class'=>'form-control', 'id'=>'titulo']); ?>
            <?php echo $this->Form->input('mensagem', ['class'=>'form-control', 'id'=>'mensagem']); ?>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12">
            <?php echo $this->Form->input('user_destino_id', ['class'=>'form-control', 'options' => $userDestinos,'type' => 'select']); ?>
        </div>
    </div>
</div>
<div class="modal-footer">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <?php echo $this->Form->button('Salvar',['class'=>'btn btn-success btn-sm']); ?>
            <?php echo $this->Form->button('Limpar',['type'=>'reset', 'class'=>'btn btn-warning btn-sm']); ?>
        </div>
    </div>  
</div>
<?php echo $this->Form->end(); ?>
<script>
    $(function () { 

        $('body').on('hidden.bs.modal', '.modal', function () {
            $(this).removeData('bs.modal');
        });
        $("#FormAddMensagem").submit(function(){
            if(!validarForm()){
                return false;
            }else{
                return true;
            }
        });
    });

    function validarForm(){
        if($("#titulo").val() == ""){
            alert("Preencha o titulo da mensagem!");
            return false;
        }else if($("#mensagem").val() == ""){
            alert("Digite uma mensagem!");
            return false;
        }else{
            return true;
        }
    }
</script>

src/Template/Mensagens/edit.ctp
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Enviar Mensagem</h4>
</div>
<?php echo $this->Form->create($mensagem,['role'=>'form', 'id'=>'FormAddCurso','method'=>'post']); ?>
<div class="modal-body">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <?= $this->Flash->render() ?>
        <div class="clearfix"></div>
    </div> 
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <?php echo $this->Form->input('titulo', ['class'=>'form-control', 'id'=>'titulo']); ?>
            <?php echo $this->Form->input('mensagem', ['class'=>'form-control', 'id'=>'mensagem']); ?>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12">
            <?php echo $this->Form->input('user_destino_id', ['class'=>'form-control', 'options' => $userDestinos,'type' => 'select']); ?>
        </div>
    </div>
</div>
<div class="modal-footer">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <?php echo $this->Form->button('Salvar',['class'=>'btn btn-success btn-sm']); ?>
            <?php echo $this->Form->button('Limpar',['type'=>'reset', 'class'=>'btn btn-warning btn-sm']); ?>
        </div>
    </div>  
</div>
<?php echo $this->Form->end(); ?>
<script>
    $(function () { 

        $('body').on('hidden.bs.modal', '.modal', function () {
            $(this).removeData('bs.modal');
        });
        $("#FormAddCurso").submit(function(){
            if(!validarForm()){
                return false;
            }else{
                return true;
            }
        });
    });

    function validarForm(){
        if($("#nome").val() == ""){
            alert("Preencha o nome do curso!");
            return false;
        }else if($("#descricao").val() == ""){
            alert("Preencha a descrição do curso!");
            return false;
        }else if($("#quantidade_periodo").val() == ""){
            alert("Preencha a quantidade de períodos do curso!");
            return false;
        }else if($("#quantidade_hora_complementar").val() == ""){
            alert("Preencha a quantidade de horas complementares do curso!");
            return false;
        }else if($("#categoria").val() == ""){
            alert("Preencha a categoria do curso!");
            return false;
        }else{
            return true;
        }
    }
</script>

src/Template/Mensagens/enviadas.ctp
<?php echo $this->Html->css('dataTables.bootstrap.css') ?>
<?php echo $this->Html->css('responsive.bootstrap.css') ?>
<?php echo $this->Html->css('buttons.bootstrap.css') ?>
<?php echo $this->Html->css('fixedHeader.bootstrap.css') ?>
<?php echo $this->Html->css('scroller.bootstrap.css') ?>

<div class="page-title">
    <div class="title_left">
        <h3>Mensagens</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <?php echo $this->Html->link('Adicionar', ['action'=>'add'], ['escape'=>false,'class' => 'btn btn-success btn-sm', 'data-toggle'=>'modal','data-target'=>'#AddMensagem']); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <?= $this->Flash->render() ?>
                    <div class="clearfix"></div>
                </div> 
                <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info">
                    <thead>
                        <tr role="row">
                            <th>Id</th>
                            <th>Título</th>
                            <th>Mensagem</th>
                            <th>Destinatário</th>
                            <th>Situação</th>
                            <th>Opções</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($mensagens as $mensagem): ?>
                            <tr>
                                <td><?php echo $mensagem->id; ?></td>
                                <td><?php echo $mensagem->titulo; ?></td>
                                <td><?php echo $mensagem->mensagem; ?></td>
                                <td><?php echo $mensagem->user->nome; ?></td>
                                <td><?php 
                                        if($mensagem->status == 1)
                                            echo "Não lida";
                                        else if($mensagem->status == 2)
                                            echo "Lida";
                                    ?>    
                                </td>
                                <td>
                                    <?php if($mensagem->status == 1){
                                            echo $this->Html->link('Editar', ['action'=>'edit',$mensagem->id], ['escape'=>false,'class' => 'btn btn-warning btn-xs', 'data-toggle'=>'modal','data-target'=>'#EditMensagem']);
                                            echo $this->Form->postLink('Excluir',['action' => 'delete', $mensagem->id], ['type'=>'button','class' => 'btn btn-danger btn-xs', 'escape' => false,'confirm' =>'Tem certeza que deseja excluir essa mensagem?']); 
                                        }
                                    ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade bs-example-modal" tabindex="-1" role="dialog" aria-hidden="true"  id="AddMensagem">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
</div>
<div class="modal fade bs-example-modal" tabindex="-1" role="dialog" aria-hidden="true"  id="EditMensagem">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
</div>
<?php echo $this->Html->script('jquery.dataTables') ?>
<?php echo $this->Html->script('dataTables.bootstrap') ?>
<?php echo $this->Html->script('dataTables.responsive') ?>
<?php echo $this->Html->script('responsive.bootstrap') ?>

src/Template/Mensagens/index.ctp
<?php echo $this->Html->css('dataTables.bootstrap.css') ?>
<?php echo $this->Html->css('responsive.bootstrap.css') ?>
<?php echo $this->Html->css('buttons.bootstrap.css') ?>
<?php echo $this->Html->css('fixedHeader.bootstrap.css') ?>
<?php echo $this->Html->css('scroller.bootstrap.css') ?>

<div class="page-title">
    <div class="title_left">
        <h3>Mensagens</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <?php echo $this->Html->link('Adicionar', ['action'=>'add'], ['escape'=>false,'class' => 'btn btn-success btn-sm', 'data-toggle'=>'modal','data-target'=>'#AddMensagem']); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <?= $this->Flash->render() ?>
                    <div class="clearfix"></div>
                </div> 
                <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info">
                    <thead>
                        <tr role="row">
                            <th>Id</th>
                            <th>Título</th>
                            <th>Mensagem</th>
                            <th>Destinatário</th>
                            <th>Situação</th>
                            <th>Opções</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($mensagens as $mensagem): ?>
                            <tr>
                                <td><?php echo $mensagem->id; ?></td>
                                <td><?php echo $mensagem->titulo; ?></td>
                                <td><?php echo $mensagem->mensagem; ?></td>
                                <td><?php echo $mensagem->user->nome; ?></td>
                                <td><?php 
                                        if($mensagem->status == 1)
                                            echo "Não lida";
                                        else if($mensagem->status == 2)
                                            echo "Lida";
                                    ?>    
                                </td>
                                <td>
                                    <?php if($mensagem->status == 1){
                                            echo $this->Form->postLink('Marcar como Lida',['action' => 'lerMensagem', $mensagem->id], ['type'=>'button','class' => 'btn btn-danger btn-xs', 'escape' => false]); 
                                        }
                                    ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade bs-example-modal" tabindex="-1" role="dialog" aria-hidden="true"  id="AddMensagem">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
</div>
<div class="modal fade bs-example-modal" tabindex="-1" role="dialog" aria-hidden="true"  id="EditMensagem">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
</div>
<?php echo $this->Html->script('jquery.dataTables') ?>
<?php echo $this->Html->script('dataTables.bootstrap') ?>
<?php echo $this->Html->script('dataTables.responsive') ?>
<?php echo $this->Html->script('responsive.bootstrap') ?>

src/Template/Mensagens/view.ctp
<?php
/**
  * @var \App\View\AppView $this
  * @var \App\Model\Entity\Mensagen $mensagen
  */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('Edit Mensagen'), ['action' => 'edit', $mensagen->id]) ?> </li>
        <li><?= $this->Form->postLink(__('Delete Mensagen'), ['action' => 'delete', $mensagen->id], ['confirm' => __('Are you sure you want to delete # {0}?', $mensagen->id)]) ?> </li>
        <li><?= $this->Html->link(__('List Mensagens'), ['action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Mensagen'), ['action' => 'add']) ?> </li>
    </ul>
</nav>
<div class="mensagens view large-9 medium-8 columns content">
    <h3><?= h($mensagen->id) ?></h3>
    <table class="vertical-table">
        <tr>
            <th scope="row"><?= __('Titulo') ?></th>
            <td><?= h($mensagen->titulo) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Id') ?></th>
            <td><?= $this->Number->format($mensagen->id) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('User Destino Id') ?></th>
            <td><?= $this->Number->format($mensagen->user_destino_id) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Status') ?></th>
            <td><?= $this->Number->format($mensagen->status) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Criado Por') ?></th>
            <td><?= $this->Number->format($mensagen->criado_por) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Modificado Por') ?></th>
            <td><?= $this->Number->format($mensagen->modificado_por) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Created') ?></th>
            <td><?= h($mensagen->created) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Modified') ?></th>
            <td><?= h($mensagen->modified) ?></td>
        </tr>
    </table>
    <div class="row">
        <h4><?= __('Mensagem') ?></h4>
        <?= $this->Text->autoParagraph(h($mensagen->mensagem)); ?>
    </div>
</div>