config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/MensagensTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Mensagens Model
 *
 * @property \App\Model\Table\UserDestinosTable|\Cake\ORM\Association\BelongsTo $UserDestinos
 *
 * @method \App\Model\Entity\Mensagen get($primaryKey, $options = [])
 * @method \App\Model\Entity\Mensagen newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Mensagen[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Mensagen|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Mensagen patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Mensagen[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Mensagen findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class MensagensTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('mensagens');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Users', [
            'foreignKey' => 'user_destino_id',
            'joinType' => 'INNER'
        ]);

        $this->belongsTo('UsuarioCriador', [
            'className' => 'Users',
            'foreignKey' => 'criado_por',
            'joinType' => 'INNER'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('titulo', 'create')
            ->notEmpty('titulo');

        $validator
            ->requirePresence('mensagem', 'create')
            ->notEmpty('mensagem');

        $validator
            ->integer('status')
            ->requirePresence('status', 'create')
            ->notEmpty('status');

        $validator
            ->integer('criado_por')
            ->requirePresence('criado_por', 'create')
            ->notEmpty('criado_por');

        $validator
            ->integer('modificado_por')
            ->requirePresence('modificado_por', 'create')
            ->notEmpty('modificado_por');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_destino_id'], 'Users'));

        return $rules;
    }
}

src/Template/Layout/ajax.ctp
<?php
/**
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @since         0.10.0
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */
?>
<?= $this->fetch('content') ?>

src/Template/Layout/default.ctp
<?php

$cakeDescription = 'ATIVO';
?>
<!DOCTYPE html>
<html>
<head>
    <?= $this->Html->charset() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        <?= $cakeDescription ?>:
        <?= $this->fetch('title') ?>
    </title>
    <?= $this->Html->meta('icon') ?>
    <?= $this->Html->css('bootstrap.css') ?>
    <?= $this->Html->css('font-awesome.css') ?>
    <?= $this->Html->css('custom.css') ?>

    <?= $this->fetch('meta') ?>
    <?= $this->fetch('css') ?>
    <?= $this->fetch('script') ?>
    <?php echo $this->Html->script('jquery') ?>
    <?php echo $this->Html->script('bootstrap') ?>
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                       <!-- <a href="" class="site_title"><i class="fa fa-paw"></i> <span>ATIVO</span></a>-->
                       <center><?php echo $this->Html->image('ativo.jpg', ['width'=>'140px','heigth'=>'170px']); ?></center>
                    </div>
                    <div class="clearfix"></div>
                    <div class="profile clearfix">
                      <div class="profile_info">
                        <center><span>Bem vindo,</span>
                        <h2><?php echo $userLogado->nome; ?></h2></center>
                      </div>
                    </div>
                    <br />
                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>Menu</h3>
                            <ul class="nav side-menu">
                            <?php if($userLogado->perfil_id == 1){ ?>
                            
                                <li><a><i class="fa fa-home"></i> Administrador <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                      <li><?php echo $this->Html->link('Cursos', ['action' => 'index', 'controller' => 'Cursos'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Perfis', ['action' => 'index', 'controller' => 'Perfis'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Usuários', ['action' => 'index', 'controller' => 'Users'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Categorias de Atividades', ['action' => 'index', 'controller' => 'Categorias'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Atividades', ['action' => 'index', 'controller' => 'Atividades'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Avaliar Atividades', ['action' => 'avaliarAtividade', 'controller' => 'Atividades'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Caixa de entrada', ['action' => 'index', 'controller' => 'Mensagens'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Mensagens Enviadas', ['action' => 'enviadas', 'controller' => 'Mensagens'], ['escape'=>false]) ?></li>
    
                                    </ul>
                                </li>
                            <?php }else if($userLogado->perfil_id == 2){ ?>

                                <li><a><i class="fa fa-home"></i> Aluno <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                      <li><?php echo $this->Html->link('Progesso', ['action' => 'dashboardAluno', 'controller' => 'Atividades'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Atividades', ['action' => 'index', 'controller' => 'Atividades'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Caixa de entrada', ['action' => 'index', 'controller' => 'Mensagens'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Mensagens Enviadas', ['action' => 'enviadas', 'controller' => 'Mensagens'], ['escape'=>false]) ?></li>
                                    </ul>
                                </li>
                            <?php }else if($userLogado->perfil_id == 3){ ?>
                                <li><a><i class="fa fa-home"></i> Coordenador <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                      <li><?php echo $this->Html->link('Progesso', ['action' => 'dashboardAluno', 'controller' => 'Atividades'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Atividades', ['action' => 'index', 'controller' => 'Atividades'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Usuários', ['action' => 'index', 'controller' => 'Users'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Categorias de Atividades', ['action' => 'index', 'controller' => 'Categorias'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Avaliar Atividades', ['action' => 'avaliarAtividade', 'controller' => 'Atividades'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Caixa de entrada', ['action' => 'index', 'controller' => 'Mensagens'], ['escape'=>false]) ?></li>
                                      <li><?php echo $this->Html->link('Mensagens Enviadas', ['action' => 'enviadas', 'controller' => 'Mensagens'], ['escape'=>false]) ?></li>
                                      
                                    </ul>
                                </li>
                            <?php } ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <?php echo $userLogado->nome; ?>
                                    <span class=" fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><?= $this->Html->link('Sair', ['controller' => 'Users', 'action' => 'logout'],  array('escape' => false)) ?>
                                    </li>
                                </ul>
                            </li>

                            <li role="presentation" class="dropdown">
                                <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-envelope-o"></i>
                                    <span class="badge bg-green"></span>
                                </a>
                                <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                    <?php if(!empty($mensagensDefault)){
                                            foreach ($mensagensDefault as $key => $mensagem) { ?>
                                                <li>
                                                    <a> 
                                                        <span>
                                                            <span><?php echo $mensagem->usuario_criador->nome; ?> </span>
                                                        </span>
                                                        <span class="message"><?php echo $mensagem->mensagem; ?></span>
                                                    </a>
                                                </li>
                                            <?php } ?>
                                        <?php }else{ ?>
                                                <li>
                                                    <a> 
                                                        <span class="message"><?php echo "Sem mensagens para exibir"; ?></span>
                                                    </a>
                                                </li>
                                            <?php } ?>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="right_col" role="main">
                <?php echo $this->fetch('content') ?>
            </div>
            <footer>
                <div class="pull-right">
                    ATIVO - SISTEMA GERENCIADOR DE ATIVIDADES COMPLEMENTARES
                </div>
                <div class="clearfix"></div>
            </footer>
        </div>
    </div>
    <?php echo $this->Html->script('custom') ?>
</body>
</html>

src/Template/Layout/error.ctp
<?php
/**
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @since         0.10.0
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */
?>
<!DOCTYPE html>
<html>
<head>
    <?= $this->Html->charset() ?>
    <title>
        <?= $this->fetch('title') ?>
    </title>
    <?= $this->Html->meta('icon') ?>

    <?= $this->Html->css('base.css') ?>
    <?= $this->Html->css('cake.css') ?>

    <?= $this->fetch('meta') ?>
    <?= $this->fetch('css') ?>
    <?= $this->fetch('script') ?>
</head>
<body>
    <div id="container">
        <div id="header">
            <h1><?= __('Error') ?></h1>
        </div>
        <div id="content">
            <?= $this->Flash->render() ?>

            <?= $this->fetch('content') ?>
        </div>
        <div id="footer">
            <?= $this->Html->link(__('Back'), 'javascript:history.back()') ?>
        </div>
    </div>
</body>
</html>

src/Template/Layout/inicial.ctp
<?php

$cakeDescription = 'ATIVO';
?>
<!DOCTYPE html>
<html>
<head>
    <?= $this->Html->charset() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        <?= $cakeDescription ?>:
        <?= $this->fetch('title') ?>
    </title>
    <?= $this->Html->meta('icon') ?>

    <?= $this->Html->css('bootstrap.css') ?>
    <?= $this->Html->css('font-awesome.css') ?>
    <?= $this->Html->css('nprogress.css') ?>
    <?= $this->Html->css('animate.css') ?>
    <?= $this->Html->css('custom.css') ?>
    
    <?= $this->fetch('meta') ?>
    <?= $this->fetch('css') ?>
    <?= $this->fetch('script') ?>
</head>
<body class="login">
    <?= $this->fetch('content') ?>
</body>
</html>